//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKKO_DUMM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EKKO_DUMM()
        {
            this.EKPO_DUMM = new HashSet<EKPO_DUMM>();
        }
    
        public string EBELN { get; set; }
        public string LIFNR { get; set; }
        public string BEDAT { get; set; }
        public string BUKRS { get; set; }
        public string ZTERM { get; set; }
        public string EKORG { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> WKURS { get; set; }
        public Nullable<decimal> RETPC { get; set; }
        public Nullable<decimal> DPPCT { get; set; }
        public Nullable<decimal> DPAMT { get; set; }
        public Nullable<decimal> FONDOG { get; set; }
        public Nullable<decimal> RET_FONDOG { get; set; }
        public Nullable<decimal> RES_FONDOG { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> POR_ANTICIPO { get; set; }
        public Nullable<decimal> POR_FONDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EKPO_DUMM> EKPO_DUMM { get; set; }
    }
}
